config/routes.rb
Vzaar::Application.routes.draw do
  root :to => "permutations#index"

  match "search" => "permutations#search", :as => :search
  match "upload" => "permutations#upload", :as => :upload

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/permutations_controller.rb
require 'benchmark'
require 'permuter'

class PermutationsController < ApplicationController
  include PermutationsHelper
  attr_accessor :search_results, :search_time
  helper_method :search_results, :search_time

  def index
  end

  def search
    head :not_found and return unless permuter

    @search_results = permuter.words_from(params[:q])
    @search_time = permuter.last_search_time
  end
  
  def upload
    self.permuter = Permuter.load(params[:dictionary].tempfile, params[:dictionary].original_filename)
    redirect_to root_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/permutations_helper.rb
module PermutationsHelper
  def permuter_loaded?
    session[:permuter_id].present? && permuter
  end
  
  def permuter_name
    permuter.name if permuter_loaded?
  end

protected
  def permuter
    if id = session[:permuter_id]
      (Thread.current[:permuters] ||= {})[id]
    end
  end

  def permuter=(permuter)
    session[:permuter_id] = permuter.id
    (Thread.current[:permuters] ||= {})[permuter.id] = permuter
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vzaar - Permuter</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/permutations/_search.json.erb
<li>
  <time><%= Time.now.to_s(:db) %></time>
  <span class="meta">
    <%= pluralize(words.size, 'result') %> found for ‘<%= term %>’ in
    <%= (permutation_time*1000).round(4) %>ms
  </span>
  <% if words.any? %>
  <ul class="anagrams">
    <%= words.map { |word| content_tag(:li, word) }.inject(:+) %>
  </ul>
  <% end %>
</li>

app/views/permutations/index.html.erb
<h1>Permuter</h1>
<section>
  <%= form_tag(upload_path, :multipart => true, :id => 'upload') do %>
    <%= file_field_tag :dictionary %>
    <%= submit_tag "Upload a new dictionary" %>
  <% end %>
  <p id="status">
    <% if permuter_loaded? %>
      <%= permuter_name %>
    <% else %>
      No dictionary currently loaded
    <% end %>
  </p>
</section>
<section>
  <%= form_tag(search_path, :remote => true, :id => 'search') do %>
    <%= label_tag :q, "Enter a word to search for anagrams." %>
    <%= text_field_tag :q %>
    <%= submit_tag "Search" %>
  <% end %>
  <ol class="results">
  </ol>
</section>

app/views/permutations/search.json.erb
<%= {
  :template => render(:partial => 'search', :locals => {
    :term => params[:q],
    :words => search_results,
    :permutation_time => search_time
  })
}.to_json.html_safe %>